Repository Azure/Enterprise-Scale, pull requests merged in 2020-08, with the labels that each got.

#148 Doc update - Adding deployment steps for WingTip Reference Implementation
  docs/reference/wingtip/README.md
  docs/reference/wingtip/media/deploy1.PNG
  docs/reference/wingtip/media/deploy2.PNG
  docs/reference/wingtip/media/deploy3.PNG
  docs/reference/wingtip/media/deploy4.PNG
  docs/reference/wingtip/media/deploy5.PNG
Labels: documentation

#155 Update Readme.md
  docs/reference/contoso/Readme.md
Labels: documentation

#154 Add Azure DevOps support
  .azure-pipelines/azops-pull.yml
  .azure-pipelines/azops-push.yml
  .github/workflows/azops-pull.yml
  .github/workflows/azops-push.yml
  README.md
  docs/Deploy/setup-azuredevops.md
Labels: enhancement

#162 Fix schedule trigger
  .azure-pipelines/azops-pull.yml
Labels: bug

#163 Schedule Defaults & Env Vars
  .azure-pipelines/azops-pull.yml
  .azure-pipelines/azops-push.yml
Labels: enhancement

#183 Fixing portal URLs
  azopsreference/README.md
Labels: bug, policy

#185 Publishing draft RI for small enterprises
  docs/reference/treyresearch/README.md
  docs/reference/treyresearch/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/treyresearch/armTemplates/auxiliary/logAnalytics.json
  docs/reference/treyresearch/armTemplates/auxiliary/security.json
  docs/reference/treyresearch/armTemplates/es-lite.json
  docs/reference/treyresearch/armTemplates/portal-es-lite.json
Labels: enhancement

#194 IAB update for AZURE_CREDENTIALS Json
  docs/enterprise-scale-iab/setup-git-cicd.md
Labels: documentation

#203 Add partialdiscovery environment variable to the Github workflows
  .github/workflows/azops-pull.yml
  .github/workflows/azops-push.yml
Labels: azops, enhancement
