Repository Azure/Enterprise-Scale, pull requests merged in 2020-07, with the labels that each got.

#53 updating reference implementation diagrams
  docs/media/icon.png
  docs/reference/adventureworks/media/es-hubspoke.png
  docs/reference/contoso/media/ns-vwan.png
  docs/reference/wingtip/media/es-without-networking.PNG
Labels: documentation

#57 fix broken links
  docs/reference/Readme.md
Labels: documentation

#55 Add VS Codespaces support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement

#60 Added support for workflow_dispatch
  .github/workflows/azops.yml
Labels: enhancement

#22 Support Azure DevOps
  .azure-pipelines/AzOps.yml
  .github/workflows/azops.yml
  README.md
  docs/Deploy/setup-azuredevops.md
Labels: enhancement

#72 Feature - Auto pull Azure Configuration
  .github/workflows/auto-azops-pull.yml
Labels: enhancement

#75 Fix - Filtering Repository name for Azure/Enterprise-Scale upstream repo
  .github/workflows/auto-azops-pull.yml
Labels: bug

#78 Add reference workflow
  .github/workflows/reference.yml
  azopsreference/.gitignore
Labels: enhancement

#81 Rename automated branch
  .github/workflows/reference.yml
Labels: bug

#82 Update reference workflow
  .github/workflows/reference.yml
Labels: enhancement

#87 Feature - rename workflow
  .github/workflows/azops-export.yml
  .github/workflows/azops-pull.yml
  .github/workflows/azops-push.yml
Labels: enhancement

#90 Doc update to refresh azopsreference folder
  docs/Deploy/deploy-new-policy-assignment.md
  docs/enterprise-scale-iab/deploy-tenant.md
  docs/enterprise-scale-iab/use-git-pipeline.md
  docs/reference/contoso/Readme.md
Labels: documentation

#91 Doc - updating gitignore filter to include Microsoft.Management and Microsoft.Subscription namespace
  azopsreference/.gitignore
Labels: enhancement

#92 Byot
  README.md
  docs/Deploy/deploy-new-arm.md
  docs/Deploy/media/deployment-scopes.png
  docs/Deploy/media/sample-deployment-scope.png
Labels: documentation

#93 Fix - azopsreference export workflow
  .github/workflows/azops-export.yml
Labels: bug

#101 Renaming workflow name
  .github/workflows/azops-export.yml
  .github/workflows/azops-pull.yml
  .github/workflows/azops-push.yml
Labels: enhancement

#106 Fixing code formatting
  docs/Deploy/setup-github.md
Labels: documentation

#107 Feature Added validation to run pull workflow if AZURE_CREDENTIALS secret is available
  .github/workflows/azops-pull.yml
Labels: enhancement

#108 Disable auto-merge
  .github/workflows/azops-export.yml
Labels: bug

#123 refresh and next steps
  docs/reference/contoso/e2e-landing-zone-vwan-orchestration.parameters.json
  docs/reference/contoso/enterprise-scale-arm-template.json
  docs/reference/contoso/ux-vwan.json
  docs/reference/wingtip/README.md
  docs/reference/wingtip/e2e-landing-zone-foundation-orchestration.parameters.json
  docs/reference/wingtip/enterprise-scale-arm-template.json
  docs/reference/wingtip/ux-foundation.json
Labels: do not merge, documentation, enhancement
