Repository Azure/Enterprise-Scale, pull requests merged in 2021-11, with the labels that each got.

#846 Update README.md
  eslzArm/README.md
Labels: bug, documentation, engineering

#850 Add parameter for budget name to Deploy-Budget policy
  .gitignore
  docs/ESLZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/gov/fairfaxPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: enhancement, policy, engineering

#855 Fix What's New Formatting
  docs/wiki/Whats-new.md
Labels: bug, documentation

#858 November 2021 Community Call Additon
  docs/wiki/Community-Calls.md
  docs/wiki/Whats-new.md
  docs/wiki/media/community-calls/nov-2021/ESLZ-Community-Call-17112021.pdf
  docs/wiki/media/community-calls/nov-2021/eslz-nov-2021-youtube-screenshot.png
Labels: documentation

#865 Add `AuditEvent` to `Deploy-Diagnostics-AA` Policy Definition
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: enhancement, policy

#869 Add `caf-enterprise-scale` module update to the "What's New" page
  docs/wiki/Whats-new.md
Labels: documentation
