Repository Azure/Enterprise-Scale, pull requests merged in 2021-06, with the labels that each got.

#610 Typo Fix in "What is ES" wiki page
  docs/wiki/What-is-Enterprise-Scale.md
Labels: documentation

#611 Create "What's New?" page for ESLZ
  .github/PULL_REQUEST_TEMPLATE.md
  docs/wiki/Home.md
  docs/wiki/Whats-new.md
  docs/wiki/_Sidebar.md
Labels: documentation, enhancement

#614 Update "What's New?" for June 2021
  docs/wiki/Whats-new.md
Labels: documentation

#619 Update Whats New
  docs/wiki/Whats-new.md
Labels: documentation

#606 Add 'AzureBastionSubnet' exclusion for UDR on Subnets Policy
  docs/ESLZ-Policies.md
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: documentation, enhancement, policy

#622 pricing section update
  docs/wiki/What-is-Enterprise-Scale.md
  docs/wiki/Whats-new.md
Labels: documentation

#623 Whats new? - Updates 17/06/2021
  docs/wiki/Whats-new.md
Labels: documentation

#635 Fixing typo in policy article
  docs/ESLZ-Policies.md
Labels: documentation

#639 Updates to Contoso RI
  docs/reference/contoso/Readme.md
  docs/reference/contoso/media/contoso-mg-structure.png
  docs/reference/contoso/media/global-transit.png
  docs/reference/contoso/media/image11.png
  docs/reference/contoso/media/image5.png
  docs/reference/contoso/media/image7.png
  docs/reference/contoso/media/image9.png
  docs/reference/contoso/media/initialize-azops.png
  docs/reference/contoso/media/lz-deployment.png
  docs/reference/contoso/media/tenant-level-deployment.png
Labels: documentation

#640 Fixing issue #638
  docs/reference/adventureworks/README.md
  docs/reference/contoso/Readme.md
  docs/reference/treyresearch/README.md
  docs/reference/wingtip/README.md
Labels: bug, documentation

#641 Update Whats New
  docs/wiki/Whats-new.md
Labels: documentation, enhancement

#649 Fix VNET Peering Policies
  docs/ESLZ-Policies.md
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
  docs/wiki/Whats-new.md
Labels: bug, documentation, policy

#650 Formatting issue resolved
  docs/wiki/Whats-new.md
Labels: documentation

#630 Update Deny-Subnet-Without-Nsg Policy to Allow Subnet Exclusions
  docs/ESLZ-Policies.md
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
  docs/wiki/Whats-new.md
Labels: documentation, enhancement, policy
