Repository Azure/Enterprise-Scale, pull requests merged in 2021-07, with the labels that each got.

#666 Grammar fix
  docs/wiki/What-is-Enterprise-Scale.md
Labels: documentation

#667 Add whats new to README.md
  README.md
Labels: documentation

#669 Removing duplicated word
  docs/ESLZ-Policies.md
Labels: documentation

#681 13/07/2021 Whats New? - Update
  docs/wiki/Whats-new.md
Labels: documentation

#613 adding ARM modules
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/mgmtGroupStructure/mgmtGroups.json
  eslzArm/managementGroupTemplates/mgmtGroupStructure/mgmtGroupsLite.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-AksPrivEscalationPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-AksPrivilegedPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-AksWithoutHttpsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-DINE-APPEND-TLS-SSL-PolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-IPForwardingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicEndpointPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicIpAddressPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-RDPFromInternetPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-StorageWithoutHttpsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-SubnetWithoutNsgPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ASBPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ASCConfigPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ActivityLogPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-AksPolicyPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-LogAnalyticsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-PrivateDNSZonesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ResourceDiagnosticsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-SQLAuditingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-SQLEncryptionPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-VMBackupPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-VMMonitoringPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-VMSSMonitoringPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/MODIFY-DDoSPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/DINE-PrivateDNSZonesPolicySetDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/Deny-PublicEndpointsPolicySetDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/managementGroupTemplates/roleAssignments/azOpsRoleAssignment.json
  eslzArm/managementGroupTemplates/roleAssignments/roleAssignment.json
  eslzArm/managementGroupTemplates/subscriptionOrganization/subscriptionOrganization.json
  eslzArm/portal backup.json
  eslzArm/resourceGroupTemplates/azOpsArm.json
  eslzArm/resourceGroupTemplates/azureFirewall.json
  eslzArm/resourceGroupTemplates/ddosProtection.json
  eslzArm/resourceGroupTemplates/expressRouteCircuit.json
  eslzArm/resourceGroupTemplates/privateDnsZones.json
  eslzArm/subscriptionTemplates/ascConfiguration.json
  eslzArm/subscriptionTemplates/azActivityDiagnostics.json
  eslzArm/subscriptionTemplates/corp-vnet-peering.json
  eslzArm/subscriptionTemplates/hubspoke-connectivity.json
  eslzArm/subscriptionTemplates/logAnalyticsSolutions.json
  eslzArm/subscriptionTemplates/logAnalyticsWorkspace.json
  eslzArm/subscriptionTemplates/nvahubspoke-connectivity.json
  eslzArm/subscriptionTemplates/resourceGroup.json
  eslzArm/subscriptionTemplates/vnetPeering.json
  eslzArm/subscriptionTemplates/vnetPeeringVwan.json
  eslzArm/subscriptionTemplates/vpnGateway.json
  eslzArm/subscriptionTemplates/vwan-connectivity.json
Labels: documentation, enhancement, policy

#684 new RI update
  README.md
  docs/EnterpriseScale-Deploy-reference-implentations.md
  docs/reference/adventureworks/README.md
  docs/reference/contoso/Readme.md
  docs/reference/wingtip/README.md
Labels: enhancement

#687 Updates to RIs documents
  docs/reference/adventureworks/README.md
  docs/reference/contoso/Readme.md
  docs/reference/wingtip/README.md
Labels: documentation

#689 User guide update
  docs/wiki/Deploying-Enterprise-Scale.md
  docs/wiki/media/ESLZ-Company-Prefix.JPG
  docs/wiki/media/clip_image010.jpg
  docs/wiki/media/clip_image014.jpg
  docs/wiki/media/clip_image015.png
  docs/wiki/media/clip_image020.jpg
  docs/wiki/media/clip_image022.png
  docs/wiki/media/clip_image024.png
  docs/wiki/media/clip_image026.png
  docs/wiki/media/clip_image028.jpg
  docs/wiki/media/clip_image030.jpg
  docs/wiki/media/clip_image032.jpg
  docs/wiki/media/clip_image034.png
  docs/wiki/media/clip_image035.png
  docs/wiki/media/clip_image036a.png
  docs/wiki/media/clip_image036b.png
  docs/wiki/media/clip_image036c.png
  docs/wiki/media/clip_image037.jpg
  docs/wiki/media/clip_image039.jpg
Labels: documentation

#682 What's New Updates for ARM Module Changes
  docs/ESLZ-Policies.md
  docs/wiki/Whats-new.md
Labels: documentation

#692 Fix for Deploy-Diagnostics-LogicAppsWF Not Assigned #691 & Updating NSG, UDR & VNET Peering policies to versions they were before in RIs
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: documentation, policy

#673 Update readme links and commands
  examples/policies/policy-definition/README.md
Labels: documentation, waiting for response

#701 renaming ESLZ to ALZ
  eslzArm/eslz-portal.json
Labels: documentation

#710 AzOps 1.3.1 Added to What's New Page
  docs/wiki/Whats-new.md
Labels: documentation

#712 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#713 Added ARO public IP requirement
  workloads/ARO/README.md
Labels: triage
