Repository Azure/Enterprise-Scale, pull requests merged in 2021-12, with the labels that each got.

#875 Change wording and link
  docs/Deploy/deploy-lz-vnet.md
Labels: bug, documentation

#822 Option for enforcementMode
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
Labels: engineering

#880 What's New - Further December 2021 updates
  docs/wiki/Whats-new.md
  docs/wiki/media/caf-docs-mstone-2-toc.png
Labels: documentation
