Repository Azure/Enterprise-Scale, pull requests merged in 2021-09, with the labels that each got.

#757 Databricks Custom Policies
  eslzArm/managementGroupTemplates/policyDefinitions/DENY-DatabricksPublicIpPolicyDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/DENY-DatabricksSkuPolicyDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/DENY-DatabricksVirtualNetworkPolicyDefinition.json
Labels: enhancement

#780 Validate VPN/ER Gateway Subnet CIDR Range
  eslzArm/eslz-portal.json
Labels: enhancement, engineering

#784 Validation updates
  eslzArm/eslz-portal.json
Labels: enhancement, engineering

#786 Added Data Policies File
  eslzArm/managementGroupTemplates/policyDefinitions/DENY-DatabricksPublicIpPolicyDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/DENY-DatabricksSkuPolicyDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/DENY-DatabricksVirtualNetworkPolicyDefinition.json
  eslzArm/managementGroupTemplates/policyDefinitions/dataPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: enhancement, engineering

#794 Simplify Visibility Condition
  eslzArm/eslz-portal.json
Labels: enhancement, engineering

#793 Add Option to select Firewall SKU
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/subscriptionTemplates/hubspoke-connectivity.json
  eslzArm/subscriptionTemplates/vwan-connectivity.json
Labels: enhancement, engineering

#778 Adding policies for Databricks workloads
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-DatabricksPipPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-DatabricksSkuPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-DatabricksVnetPolicyAssignment.json
Labels: enhancement, engineering

#800 Identity subnet size
  eslzArm/eslz-portal.json
Labels: enhancement

#799 Fix VWAN Portal Requirements
  eslzArm/eslz-portal.json
Labels: bug, engineering

#801 updated uri's to call generic template blade
  docs/reference/wingtip/README.md
Labels: engineering

#805 Fix Databricks policy assignments failing
  eslzArm/eslzArm.json
Labels: bug, engineering

#807 Added AML Policy to Disable Public Network Access
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/dataPolicies.json
Labels: enhancement, engineering

#808 Add September to TOC and typo for AzOps version number
  docs/wiki/Whats-new.md
Labels: documentation

#809 Added reference to Enterprise-Scale Analytics
  docs/wiki/Whats-new.md
  workloads/data/README.md
  workloads/data/docs/media/EnterpriseScaleAnalytics.gif
Labels: documentation

#817 Fix "community call" navigation item on README.md
  README.md
Labels: documentation
