Repository Azure/Enterprise-Scale, pull requests merged in 2021-03, with the labels that each got.

#429 Ri refreshv3
  docs/reference/adventureworks/armTemplates/auxiliary/corp-peering-copy.json
  docs/reference/adventureworks/armTemplates/auxiliary/corp-policy-peering.json
  docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/adventureworks/armTemplates/auxiliary/identity.json
  docs/reference/adventureworks/armTemplates/auxiliary/logAnalytics.json
  docs/reference/adventureworks/armTemplates/auxiliary/logAnalyticsSolutions.json
  docs/reference/adventureworks/armTemplates/auxiliary/lz.json
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/contoso/armTemplates/auxiliary/identity.json
  docs/reference/contoso/armTemplates/auxiliary/logAnalytics.json
  docs/reference/contoso/armTemplates/auxiliary/logAnalyticsSolutions.json
  docs/reference/contoso/armTemplates/auxiliary/lz.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/vwan-connectivity.json
  docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/wingtip/armTemplates/auxiliary/logAnalytics.json
  docs/reference/wingtip/armTemplates/auxiliary/logAnalyticsSolutions.json
  docs/reference/wingtip/armTemplates/auxiliary/lz.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: do not merge, enhancement, policy

#434 More comprehensive Azure DevOps docs
  docs/Deploy/setup-azuredevops.md
  docs/EnterpriseScale-Setup-azure.md
  docs/media/ado-add-build-policy.png
  docs/media/ado-complete-pr.png
  docs/media/ado-env-approval.png
  docs/media/ado-import-repo.png
  docs/media/ado-manage-repo.png
  docs/media/ado-permissions-group.png
  docs/media/ado-pipeline-create.png
  docs/media/ado-pipeline-variable.png
  docs/media/ado-repo-buildservice.png
  docs/media/ado-repo-forcepush.png
  docs/media/ado-repo-policy.png
Labels: documentation

#452 Added support for AZs
  docs/reference/adventureworks/README.md
Labels: documentation

#426 Update root prefix allowed length to 10 characters
  docs/reference/adventureworks/armTemplates/auxiliary/corp-peering-copy.json
  docs/reference/adventureworks/armTemplates/auxiliary/corp-policy-peering.json
  docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/adventureworks/armTemplates/auxiliary/identity.json
  docs/reference/adventureworks/armTemplates/auxiliary/logAnalytics.json
  docs/reference/adventureworks/armTemplates/auxiliary/logAnalyticsSolutions.json
  docs/reference/adventureworks/armTemplates/auxiliary/lz.json
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/adventureworks/armTemplates/es-hubspoke.json
  docs/reference/adventureworks/armTemplates/portal-es-hubspoke.json
  docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/contoso/armTemplates/auxiliary/identity.json
  docs/reference/contoso/armTemplates/auxiliary/logAnalytics.json
  docs/reference/contoso/armTemplates/auxiliary/logAnalyticsSolutions.json
  docs/reference/contoso/armTemplates/auxiliary/lz.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/vwan-connectivity.json
  docs/reference/contoso/armTemplates/es-vwan.json
  docs/reference/contoso/armTemplates/portal-es-vwan.json
  docs/reference/treyresearch/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/treyresearch/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/treyresearch/armTemplates/auxiliary/logAnalytics.json
  docs/reference/treyresearch/armTemplates/auxiliary/lz.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/es-lite.json
  docs/reference/treyresearch/armTemplates/portal-es-lite.json
  docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/wingtip/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/wingtip/armTemplates/auxiliary/logAnalytics.json
  docs/reference/wingtip/armTemplates/auxiliary/logAnalyticsSolutions.json
  docs/reference/wingtip/armTemplates/auxiliary/lz.json
  docs/reference/wingtip/armTemplates/auxiliary/mkPolicies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/vwan-connectivity.json
  docs/reference/wingtip/armTemplates/es-add-hub.json
  docs/reference/wingtip/armTemplates/es-add-vwan.json
  docs/reference/wingtip/armTemplates/es-foundation.json
  docs/reference/wingtip/armTemplates/portal-es-add-hub.json
  docs/reference/wingtip/armTemplates/portal-es-add-vwan.json
  docs/reference/wingtip/armTemplates/portal-es-foundation.json
  examples/landing-zones/subscription-with-rbac/README.md
  examples/landing-zones/subscription-with-rbac/portal-subscriptionWithRbac.json
  examples/landing-zones/subscription-with-rbac/subscriptionWithRbac.json
Labels: enhancement

#474 Fix incorrect character cases
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: bug

#475 Fix character casing for "type": "String"
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: bug
