Repository Azure/Enterprise-Scale, pull requests merged in 2021-08, with the labels that each got.

#723 Update Az CLI Azure AD Query Output For Bash In User Guide
  docs/wiki/Deploying-Enterprise-Scale.md
Labels: bug, documentation

#727 Patch ESLZ ARM
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-SubnetWithoutNsgPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: bug

#718 Portal UX - Fix VWAN Address Space & Remove AzFW Subnet For VWAN
  eslzArm/eslz-portal.json
  eslzArm/subscriptionTemplates/hubspoke-connectivity.json
  eslzArm/subscriptionTemplates/nvahubspoke-connectivity.json
  eslzArm/subscriptionTemplates/vwan-connectivity.json
Labels: bug, enhancement

#745 What's New Updates - August 19th
  docs/wiki/Whats-new.md
Labels: documentation

#749 Update What's New with EA Doc Update
  docs/wiki/Whats-new.md
Labels: documentation

#770 Add August 2021 Community Call Resources
  README.md
  docs/wiki/Community-Calls.md
  docs/wiki/Home.md
  docs/wiki/Whats-new.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/community-calls/aug-2021/ESLZ-Community-Call-25082021.pdf
  docs/wiki/media/community-calls/aug-2021/eslz-aug-2021-youtube-screenshot.png
Labels: documentation, enhancement
