Repository Azure/Enterprise-Scale, pull requests merged in 2021-04, with the labels that each got.

#482 Consistent Policy Name Casing
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: bug

#497 Adding FAQ for Subscription Picker UI
  docs/EnterpriseScale-FAQ.md
Labels: documentation

#479 Amendment to Powershell script
  docs/EnterpriseScale-Setup-aad-permissions.md
Labels: documentation

#523 Update enable-subscription-creation.md
  docs/Deploy/enable-subscription-creation.md
Labels: documentation

#531 ESLZ networking updates for Adventure Works
  docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/adventureworks/armTemplates/es-hubspoke.json
  docs/reference/adventureworks/armTemplates/es-portal.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: enhancement, policy

#542 Enhancing connectivity section
  docs/reference/adventureworks/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/reference/adventureworks/armTemplates/es-hubspoke.json
  docs/reference/adventureworks/armTemplates/es-portal.json
Labels: enhancement

#533 Update parameters for Deploy-ASC-Config initiative
  docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: bug
