Repository Azure/Enterprise-Scale, pull requests merged in 2021-05, with the labels that each got.

#550 update FAQ
  docs/EnterpriseScale-FAQ.md
Labels: do not merge

#577 Update policy mode Indexed->All for TLS version
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
Labels: bug

#575 ESLZ May Update
  docs/reference/adventureworks/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/adventureworks/armTemplates/auxiliary/policies.json
  docs/reference/adventureworks/armTemplates/es-portal.json
  docs/reference/contoso/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/contoso/armTemplates/auxiliary/policies.json
  docs/reference/contoso/armTemplates/es-portal.json
  docs/reference/wingtip/armTemplates/auxiliary/diagnosticsAndSecurity.json
  docs/reference/wingtip/armTemplates/auxiliary/policies.json
  docs/reference/wingtip/armTemplates/es-portal.json
Labels: enhancement

#587 adding policy index
  docs/ESLZ-Policies.md
Labels: documentation, policy

#590 Update Adventure Works RI Networking Information
  docs/media/es-hubspoke-nw.png
  docs/reference/adventureworks/README.md
  docs/reference/adventureworks/media/hub-and-spoke-topology.png
Labels: documentation, enhancement
