Repository Azure/Enterprise-Scale, pull requests merged in 2022-07, with the labels that each got.

#1003 Add latest ALZ TF module updates
  docs/wiki/Whats-new.md
Labels: documentation

#1006 Azure backup DNS zone geo code fix and docs
  .github/PULL_REQUEST_TEMPLATE.md
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
Labels: bug, enhancement, engineering

#1009 Fix #1008 Docs Issue
  docs/Deploy/deploy-new-policy-assignment.md
Labels: bug, documentation
