Repository Azure/Enterprise-Scale, pull requests merged in 2022-09, with the labels that each got.

#1036 Investigate deployment issues
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
Labels: do not merge, Needs: Triage :mag:

#1043 Remove unrequired `location` for RG deployments
  eslzArm/eslzArm.json
Labels: bug, engineering

#1046 add gh to ado sync config
  .github/actions-config/gh-ado-sync-config.json
  .github/workflows/gh-ado-sync.yml
Labels: Needs: Triage :mag:

#1045 AzOps Deployment Fixes & Enable GitHub to ADO Sync
  .github/actions-config/gh-ado-sync-config.json
  .github/workflows/gh-ado-sync.yml
  eslzArm/eslzArm.json
Labels: bug, enhancement, engineering

#1066 Add missing firewall category
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Firewall.json
Labels: enhancement, policy, Needs: Author Feedback
