Repository Azure/Enterprise-Scale, pull requests merged in 2022-05, with the labels that each got.

#966 May 2022 community call upload
  docs/wiki/Community-Calls.md
  docs/wiki/Whats-new.md
  docs/wiki/media/community-calls/may-2022/ALZ-Community-Call-02052022.pdf
  docs/wiki/media/community-calls/may-2022/alz-may-2022-youtube-screenshot.png
Labels: documentation

#970 Correct typo in displayName of Deny-Storage-minTLS policy
  eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/gov/fairfaxPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: policy

#960 Vwan availability zones
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/fairfaxeslz-portal.json
  eslzArm/subscriptionTemplates/vwan-connectivity.json
Labels: enhancement, engineering

#973 Update what's new with ALZ TF module v2.0.2
  docs/wiki/Whats-new.md
Labels: documentation

#977 Make root Owner assignment in Bash more robust
  docs/EnterpriseScale-Setup-azure.md
Labels: Needs: Triage :mag:
