Repository Azure/Enterprise-Scale, pull requests merged in 2022-10, with the labels that each got.

#1069 ALZ-policy updates
  docs/ESLZ-Policies.md
Labels: documentation

#1072 Image update for policy page
  docs/media/alzPolicyAzAdvertizer.png
Labels: Needs: Triage :mag:

#1078 Improve deployment name uniqueness and fix vNet naming for ALZ Portal Accelerator
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
Labels: bug, enhancement, engineering

#1083 Fix GH to ADO Sync Bugs
  .github/workflows/gh-ado-sync.yml
Labels: enhancement, engineering

#1086 Add Bicep support to `Alz.Tools`
  src/Alz.Tools/Alz.Classes/Alz.Classes.psm1
  src/Alz.Tools/Alz.Enums/Alz.Enums.psm1
  src/Alz.Tools/functions/Alz.Tools.ps1
Labels: engineering

#1091 Create Invoke-AlzCustomPolicyCheckAgainstBuiltIn.ps1
  src/scripts/Invoke-AlzCustomPolicyCheckAgainstBuiltIn.ps1
Labels: policy, engineering

#1094 Add FAQ & Portal Warning for #1080
  docs/wiki/FAQ.md
  docs/wiki/Whats-new.md
  docs/wiki/media/mg-resource-prefix-portal.png
  eslzArm/eslz-portal.json
Labels: documentation, enhancement, engineering

#1059 Add profile name parameter to diag policies
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-AA.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-ACI.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-ACR.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-APIMgmt.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-AVDScalingPlans.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-AnalysisService.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-ApiForFHIR.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-ApplicationGateway.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Bastion.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-CDNEndpoints.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-CognitiveServices.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-CosmosDB.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-DLAnalytics.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-DataExplorerCluster.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-DataFactory.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Databricks.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-EventGridSub.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-EventGridSystemTopic.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-EventGridTopic.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-ExpressRoute.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Firewall.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-FrontDoor.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Function.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-HDInsight.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-LoadBalancer.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-LogicAppsISE.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-MariaDB.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-MediaService.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-MlWorkspace.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-MySQL.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-NIC.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-NetworkSecurityGroups.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-PostgreSQL.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-PowerBIEmbedded.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-RedisCache.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Relay.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-SQLElasticPools.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-SQLMI.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-SignalR.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-TimeSeriesInsights.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-TrafficManager.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VM.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VMSS.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VNetGW.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VirtualNetwork.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDAppGroup.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDHostPools.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDWorkspace.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WebServerFarm.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Website.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-iotHub.json
Labels: policy

#1098 Update what's new for October 2022
  docs/wiki/Whats-new.md
Labels: documentation
