Repository Azure/Enterprise-Scale, pull requests merged in 2022-06, with the labels that each got.

#988 Add ALZ TF module release `v2.1.0` to What's New
  docs/wiki/Whats-new.md
Labels: documentation

#992 Update Diagnostic Policies For AVD, Azure Firewall, APIM, Bastion, Machine Learning Workspaces & Fix Storage SSL Enforcement & ML Cluster Remote Login
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/dataPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/gov/fairfaxPolicies.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: enhancement, policy, engineering

#993 Update EnterpriseScale-Setup-azure.md
  docs/EnterpriseScale-Setup-azure.md
  docs/wiki/Deploying-Enterprise-Scale-Pre-requisites.md
  docs/wiki/Deploying-Enterprise-Scale.md
Labels: bug, documentation
