Repository Azure/Enterprise-Scale, pull requests merged in 2022-11, with the labels that each got.

#1100 Enable Defender For Cosmos DB SKU to fix #1081
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json
Labels: enhancement, policy

#1099 Deprecated NSG Flow Log Policies
  docs/wiki/Deprecating-ALZ-Policies.md
  docs/wiki/Whats-new.md
  docs/wiki/_Sidebar.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Nsg-FlowLogs-to-LA.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Nsg-FlowLogs.json
Labels: policy

#1102 24458 Update ALZ Portal Accelerator with DDoS Std Rename to DDoS Netw…
  docs/ESLZ-Policies.md
  docs/reference/adventureworks/README.md
  docs/reference/azpol.md
  docs/reference/contoso/Readme.md
  docs/reference/treyresearch/armTemplates/auxiliary/hubspoke-connectivity.json
  docs/wiki/Deploying-ALZ-BasicSetup.md
  docs/wiki/Deploying-ALZ-Foundation.md
  docs/wiki/Deploying-ALZ-HubAndSpoke.md
  docs/wiki/Deploying-ALZ-VWAN.md
  docs/wiki/Deploying-ALZ.md
  docs/wiki/What-is-Enterprise-Scale.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/fairfaxeslz-portal.json
  eslzArm/managementGroupTemplates/policyAssignments/MODIFY-DDoSPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/subscriptionTemplates/hubspoke-connectivity.json
  eslzArm/subscriptionTemplates/nvahubspoke-connectivity.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-DDoSProtection.json
Labels: Needs: Triage :mag:

#1108 Minor policy doc update
  docs/ESLZ-Policies.md
Labels: documentation, policy

#1106 ESLZ Policies docs migration
  README.md
  docs/ESLZ-Policies.md
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Deprecating-ALZ-Policies.md
  docs/wiki/Home.md
  docs/wiki/Whats-new.md
  docs/wiki/_Sidebar.md
Labels: documentation

#1110 images and nav
  README.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Home.md
  docs/wiki/_Sidebar.md
Labels: bug, documentation

#1115 policy updated based on workitems 25022
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Website.json
Labels: bug, enhancement, policy

#1116 Update Available AZs in Portal Experience
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
Labels: enhancement, engineering

#1118 image links in alz policies
  docs/wiki/ALZ-Policies.md
  docs/wiki/media/Connectivity_v0.1.jpg
  docs/wiki/media/Corp_v0.1.jpg
  docs/wiki/media/Decom_v0.1.jpg
  docs/wiki/media/Identity_v0.1.jpg
  docs/wiki/media/IntRoot_v0.1.jpg
  docs/wiki/media/LandingZone_v0.1.jpg
  docs/wiki/media/Management_v0.1.jpg
  docs/wiki/media/MgmtGroups_Policies_v0.1.jpg
  docs/wiki/media/Online_v0.1.jpg
  docs/wiki/media/Platform_v0.1.jpg
  docs/wiki/media/Sandbox_v0.1.jpg
  docs/wiki/media/alzPolicyAzAdvertizer.png
Labels: Needs: Triage :mag:

#1103 Replace Deny-PublicIP with Not Allowed Resources
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/Whats-new.md
  eslzArm/README-AzureChina.md
  eslzArm/README.md
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicIpAddressPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-PublicIP.json
Labels: policy

#1085 Update SQL policies to fix #695
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-SecurityAlertPolicies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-Tde.json
Labels: policy

#1122 Update Deploy-Sql-SecurityAlertPolicies.json (hotfix)
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-SecurityAlertPolicies.json
Labels: policy

#1128 Correcting link pointing to old location.
  docs/wiki/ALZ-Policies.md
Labels: bug, documentation

#1126 Update databricks diagnostic setting policy
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Databricks.json
Labels: enhancement, do not merge, policy, external community contribution

#1129 Added policy "Deploy Diagnostic Settings for Log Analytics to Log Analytics workspace"
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-LogAnalytics.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json
  src/templates/policies.bicep
Labels: enhancement, policy

#1132 Patch incorrect policy initiatives
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deny-PublicPaaSEndpoints.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.AzureChinaCloud.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.AzureUSGovernment.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK.json
Labels: bug

#1120 Security center policy change
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-ASC-SecurityContacts.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.AzureChinaCloud.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.AzureUSGovernment.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json
Labels: do not merge, policy

#1109 Added new built-in Policies into the Initiative
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-PrivateDNSZonesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json
Labels: enhancement, policy, engineering

#1133 Add `defaultValue` for `PrivateDnsZoneId` parameters
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json
Labels: bug

#1134 US 24400 - Links to superseded policies
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: Needs: Triage :mag:

#1137 Rename Azure Security Benchmark to Microsoft Cloud Security Benchmark
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/README-AzureChina.md
  eslzArm/README.md
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ASBPolicyAssignment.json
  workloads/README.md
Labels: documentation, engineering

#1139 Minor typo correction MCSB v1 not v2
  docs/wiki/ALZ-Policies.md
Labels: Needs: Triage :mag:

#1140 Use -SignedIn to get current user
  docs/wiki/Deploying-ALZ-Pre-requisites.md
Labels: Needs: Triage :mag:

#1141 Fix #1073 - Update Private DNS Zones for Private Link
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
Labels: enhancement, engineering
