Repository Azure/Enterprise-Scale, pull requests merged in 2022-03, with the labels that each got.

#928 Added missing state in line 146
  docs/ESLZ-Policies.md
Labels: bug, documentation

#934 Add FabricBot Config-as-Code
  .github/fabricbot.json
Labels: enhancement, engineering, Needs: Triage :mag:

#938 Adding Customer Usage Attribution to ESLZ/ALZ ARM and Portal template
  README.md
  docs/wiki/Deploying-Enterprise-Scale-CustomerUsage.md
  docs/wiki/Home.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/cua-parameter.png
  docs/wiki/media/cua-portal-experience-disabled.jpg
  docs/wiki/media/cua-portal-experience-enabled.jpg
  docs/wiki/media/cua-resource.png
  docs/wiki/media/cua-variable.png
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
Labels: enhancement, do not merge, engineering
