Repository Azure/Enterprise-Scale, pull requests merged in 2023-11, with the labels that each got.

#1469 Fix: Wiki ALZ Azure Setup Bash command
  docs/wiki/ALZ-Setup-azure.md
  docs/wiki/Whats-new.md
Labels: documentation, PR: Safe to test :test_tube:

#1468 vWAN hub routing preference and autoscale
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/subscriptionTemplates/vwan-connectivity.json
Labels: PR: Safe to test :test_tube:

#1472 vWAN with single subscription deployment bug fix
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
Labels: bug, PR: Safe to test :test_tube:

#1474 Update AMBA version 2023-11-14
  eslzArm/eslzArm.json
Labels: PR: Safe to test :test_tube:

#1476 Updating Portal Accelerator MDFC VM Vulnerability Assessment to use mdeTVM by default
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json
Labels: policy, PR: Safe to test :test_tube:
