Repository Azure/Enterprise-Scale, pull requests merged in 2023-01, with the labels that each got.

#1168 Update Version in Docs - Fixing #1166
  docs/wiki/ALZ-Policies.md
Labels: documentation

#1167 Issue #672 - Fix SQL Vulnerability Assessment Policy
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-vulnerabilityAssessments.json
Labels: Needs: Triage :mag:

#1154 Low level document for updating ALZ custom policies
  docs/wiki/_Sidebar.md
  docs/wiki/media/1.1.update-alz-custom-policy-def-search.png
  docs/wiki/media/1.2.update-alz-custom-policy-def-name.png
  docs/wiki/media/2.1.update-alz-custom-policy-assignments.png
  docs/wiki/media/2.2.update-alz-custom-policy-delete-assignments.png
  docs/wiki/media/2.3.update-alz-custom-policy-search.png
  docs/wiki/media/2.4.update-alz-custom-policy-search.png
  docs/wiki/media/AzGovViz-ALZ-Policy-outDated.png
  docs/wiki/update-alz-custom-policies-to-latest.md
Labels: documentation, long term

#1176 ALZ Contribution Guide - Policy Naming Convention
  docs/wiki/ALZ-Contribution-Guide.md
Labels: documentation, enhancement

#1177 fix: Wiki Az Policy Titles
  docs/wiki/Migrate-ALZ-Policies-to-Built‐in.md
  docs/wiki/Update-ALZ-Custom-Policies-to-Latest.md
  docs/wiki/_Sidebar.md
Labels: documentation

#1179 Update policy-refresh
  docs/wiki/ALZ-Contribution-Guide.md
  docs/wiki/Migrate-ALZ-Policies-to-Built‐in.md
  docs/wiki/Update-ALZ-Custom-Policies-to-Latest.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/1.1.update-alz-custom-policy-def-search.png
  docs/wiki/media/1.2.update-alz-custom-policy-def-name.png
  docs/wiki/media/2.1.update-alz-custom-policy-assignments.png
  docs/wiki/media/2.2.update-alz-custom-policy-delete-assignments.png
  docs/wiki/media/2.3.update-alz-custom-policy-search.png
  docs/wiki/media/2.4.update-alz-custom-policy-search.png
  docs/wiki/media/AzGovViz-ALZ-Policy-outDated.png
Labels: Needs: Triage :mag:

#1180 removed md extensions
  docs/wiki/_Sidebar.md
Labels: Needs: Triage :mag:

#1183 Update Deny-MachineLearning-PublicAccessWhenBehindVnet.json
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-MachineLearning-PublicAccessWhenBehindVnet.json
Labels: bug, policy, external community contribution

#1175 Multiple Policy Updates - MDFC, TLS, CMK
  docs/reference/treyresearch/armTemplates/auxiliary/policies.json
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-EncryptTransit.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK.AzureChinaCloud.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK.AzureUSGovernment.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-Encryption-CMK.json
Labels: enhancement, policy, engineering

#1170 Add "Network interfaces should not have public IPs" - Corp - ADO WIT 25739
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicIpAddressOnNICPolicyAssignment.json
Labels: enhancement, policy, engineering
