Repository Azure/Enterprise-Scale, pull requests merged in 2023-04, with the labels that each got.

#1267 Update on items
  docs/wiki/Deploying-ALZ-ZTNetwork.md
Labels: Needs: Triage :mag:

#1269 What's New update ONLY
  docs/wiki/Whats-new.md
Labels: documentation

#1266 updating Deny virtual machine with un managed disk policy to Built-in
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-VMUnmanagedDiskPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-VMUnmanagedDisk.json
  src/templates/policies.bicep
Labels: policy

#1277 Portal Accelerator Bug Bix
  eslzArm/eslz-portal.json
Labels: bug

#1270 ALZ Zero Trust hub and spoke
  docs/wiki/Deploying-ALZ-ZTNetwork.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/zt1.png
  docs/wiki/media/zt2.png
  docs/wiki/media/zt3.png
  docs/wiki/media/zt4.png
  docs/wiki/media/zt5.png
  docs/wiki/media/zt6.png
Labels: documentation, enhancement, engineering

#1286 Update ENFORCE-GuardrailsKeyVaultPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-GuardrailsKeyVaultPolicyAssignment.json
Labels: policy

#1289 Spelling Fixes in Policy Definition Display Names & Descriptions
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-ALZ-Decomm.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-Guardrails-KeyVault.json
Labels: policy

#1293 Fairfax Portal RI Fix
  docs/wiki/Whats-new.md
  eslzArm/fairfaxeslz-portal.json
Labels: bug

#1292 Update Guide in ALZ Wiki to include the ALZ 1.7
  docs/wiki/Deploying-ALZ-ZTNetwork.md
  docs/wiki/media/zt5-2.png
  docs/wiki/media/zt7.png
  docs/wiki/media/zt8.png
  docs/wiki/media/zt9.png
Labels: documentation

#1217 Add Non-Compliance Messages to Policy Assignments
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyAssignments/AUDIT-AppGwWafPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/AUDIT-PeDnsZonesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/AUDIT-UnusedResourcesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-AksPrivEscalationPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-AksPrivilegedPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-AksWithoutHttpsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-ClassicResourceTypesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-DINE-APPEND-TLS-SSL-PolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-HybridNetworkingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-IPForwardingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-MgmtPortsFromInternetPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicEndpointPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicIpAddressOnNICPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-PublicIpAddressPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-StorageWithoutHttpsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-SubnetWithoutNsgPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-VMUnmanagedDiskPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ASBPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ActivityLogPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-AksPolicyPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-AtpOssDbPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-AtpSqlDbPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-LogAnalyticsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-MDEndpointsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-MDFCConfigPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-PrivateDNSZonesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ResourceDiagnosticsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-SQLAuditingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-SQLEncryptionPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-VMBackupPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-VMMonitoringPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-VMSSMonitoringPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-ALZ-DecommissionedPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-ALZ-SandboxPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-AcsbPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-GuardrailsKeyVaultPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/MODIFY-DDoSPolicyAssignment.json
Labels: policy

#1295 Publish April Community Call Content
  docs/wiki/Community-Calls.md
  docs/wiki/Whats-new.md
  docs/wiki/media/community-calls/april-2023/ALZ-Community-Call-27-04-2023.pdf
  docs/wiki/media/community-calls/april-2023/alz-april-2023-youtube-screenshot.png
Labels: documentation

#1294 ALZ Wiki Update for Managed Identities
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
Labels: Needs: Triage :mag:

#1296 Change the default on policy set definitions from null to empty array
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-ALZ-Decomm.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-ALZ-Sandbox.json
Labels: Needs: Triage :mag:

#1299 Spelling of correlation
  SUPPORT.md
Labels: Needs: Triage :mag:

#1298 Spelling correction of pre-requisites
  docs/reference/wingtip/README.md
Labels: Needs: Triage :mag:

#1297 Removed Service Map
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/fairfaxeslz-portal.json
  eslzArm/subscriptionTemplates/logAnalyticsSolutions.json
Labels: enhancement, engineering
