Repository Azure/Enterprise-Scale, pull requests merged in 2023-05, with the labels that each got.

#1304 Update Whats new
  docs/wiki/Whats-new.md
Labels: documentation

#1306 Bug - Fix case for azureIotPrivateDnsZoneId parameter in policy assignment
  eslzArm/managementGroupTemplates/policyAssignments/DINE-PrivateDNSZonesPolicyAssignment.json
Labels: Needs: Triage :mag:

#1310 PR for Portal RI DevOps removal (USER STORY 25574)
  docs/wiki/Deploying-ALZ-Platform-DevOps.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/fairfaxeslz-portal.json
  eslzArm/managementGroupTemplates/roleAssignments/azOpsRoleAssignment.json
  eslzArm/resourceGroupTemplates/azOpsArm.json
Labels: engineering

#1313 Bug Fix - Correcting a typo in the Deploy-MDFC-Config initiative.
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json
Labels: bug, policy, Area: MDFC

#1316 Remove workloads folder contents
  docs/wiki/ALZ-Deploy-workloads.md
  docs/wiki/Whats-new.md
  workloads/AKS/README.md
  workloads/AKS/armTemplates/online-aks.json
  workloads/AKS/armTemplates/portal-online-aks.json
  workloads/ARO/README.md
  workloads/README.md
  workloads/data/README.md
  workloads/data/docs/media/EnterpriseScaleAnalytics.gif
  workloads/keyvault/README.md
  workloads/keyvault/azkeyvault.bicep
  workloads/keyvault/azkeyvault.json
Labels: documentation

#1314 Add Azure Firewall basic sku to ALZ portal Accelerator
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/subscriptionTemplates/hubspoke-connectivity.json
  eslzArm/subscriptionTemplates/vwan-connectivity.json
Labels: enhancement, engineering

#1317 Updating ALZ Policy graphics to reflect changes
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  docs/wiki/media/Decom_v0.1.jpg
  docs/wiki/media/Decom_v0.1.svg
  docs/wiki/media/MgmtGroups_Policies_v0.1.jpg
  docs/wiki/media/MgmtGroups_Policies_v0.1.svg
  docs/wiki/media/Sandbox_v0.1.jpg
  docs/wiki/media/Sandbox_v0.1.svg
Labels: documentation, policy

#1322 PR for GH1319
  README.md
  docs/reference/adventureworks/README.md
  docs/reference/contoso/Readme.md
  docs/reference/wingtip/README.md
  docs/wiki/Create-Landingzones.md
  docs/wiki/Deploying-ALZ-Foundation.md
  docs/wiki/Deploying-ALZ-HubAndSpoke.md
  docs/wiki/Deploying-ALZ-Platform-DevOps.md
  docs/wiki/Deploying-ALZ-VWAN.md
  docs/wiki/Deploying-ALZ.md
  docs/wiki/Whats-new.md
Labels: documentation

#1323 Bug fix: Deny MgmtPorts
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json
Labels: bug, policy

#1321 Fixed grammar in compliance messages
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyAssignments/DENY-HybridNetworkingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-ResourceDiagnosticsPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-ALZ-SandboxPolicyAssignment.json
Labels: bug, policy

#1324 Added support for resource-specific destination table for API Management
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-APIMgmt.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json
Labels: policy

#1327 Bug fix #1326: AppService append sites with minimum TLS version to enforce
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Append-AppService-latestTLS.json
Labels: bug, policy

#1328 Wiki updates- New Policy FAQ
  docs/wiki/ALZ-Contribution-Guide.md
  docs/wiki/ALZ-Policies-FAQ.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  docs/wiki/_Sidebar.md
  docs/wiki/media/AzGovViz-ALZ-Policy.png
Labels: documentation

#1329 Fixing wiki URLs
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
Labels: documentation

#1337 Whats New Updating TOC to last 6 months only
  docs/wiki/Whats-new.md
Labels: documentation

#1334 Added support for resource-specific destination table for Firewall
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Firewall.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Diagnostics-LogAnalytics.json
Labels: policy

#1338 Main contribute guide updates
  docs/wiki/ALZ-Contribution-Guide.md
  docs/wiki/Whats-new.md
Labels: documentation

#1341 Spelling correction
  docs/wiki/Migrate-ALZ-Policies-to-Built‐in.md
Labels: documentation

#1340 Add new parameter file to ensure correct reference arch for TF sync
  eslzArm/eslzArm.terraform-sync.param.json
Labels: Needs: Triage :mag:
