Repository Azure/Enterprise-Scale, pull requests merged in 2023-06, with the labels that each got.

#1347 Spelling Correction
  examples/landing-zones/connected-subscription/README.md
Labels: documentation

#1346 Fix for Premium Firewall Deployment Issue
  eslzArm/subscriptionTemplates/hubspoke-connectivity.json
Labels: bug, engineering

#1349 Update sidebar to correspond to content
  docs/wiki/_Sidebar.md
Labels: Needs: Triage :mag:

#1339 PR for User Stories 28607-28609-28620
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-Storage-SFTP.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-Subnet-Without-Penp.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-UDR-With-Specific-NextHop.json
  src/templates/policies.bicep
Labels: policy

#1350 Adding new custom policies
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-FileServices-InsecureAuth.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-FileServices-InsecureKerberos.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-FileServices-InsecureSmbChannel.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-FileServices-InsecureSmbVersions.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-StorageAccount-CustomDomain.json
  src/templates/policies.bicep
Labels: enhancement, policy

#1353 PR to update policies.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: policy

#1364 Spelling Correction
  docs/wiki/Deploying-ALZ-BasicSetup.md
Labels: documentation, external community contribution

#1363 Diagnostic Settings for MGs
  docs/wiki/How-Enterprise-Scale-Works.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/diagSettingsMGs/diagSettingsMGs.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
Labels: enhancement, Needs: Triage :mag:
