Repository Azure/Enterprise-Scale, pull requests merged in 2023-07, with the labels that each got.

#1371 Fix #1370 - Remove DNS Proxy Option When AZ FW == Basic
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
Labels: enhancement

#1362 Feature: Policy Unittests
  .github/actions-pester/PolicyPesterTestHelper.psm1
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
  .github/workflows/unit-test-policies.yml
Labels: enhancement, policy, engineering

#1374 Change to Ubuntu Runner - Policy Unit Tests
  .github/workflows/unit-test-policies.yml
Labels: Needs: Triage :mag:

#1365 Deny-MgmtPorts-From-Internet does not always block NSG creation
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json
Labels: enhancement, policy

#1375 Bug: Fixed function results to not return string for Unit Tests
  .github/actions-pester/PolicyPesterTestHelper.psm1
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Labels: Needs: Triage :mag:

#1376 Enhance pester outputs
  .github/actions-pester/Test-ModifiedPolicies.Tests.ps1
Labels: enhancement

#1383 Add KV Guardrails Assignment to Platform Management group
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  docs/wiki/media/ALZ Policy Assignments v2.xlsx
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
Labels: policy

#1385 Enhance security on privileged workflows
  .github/workflows/test-portal.yml
  .github/workflows/unit-test-policies.yml
  .github/workflows/update-portal.yml
Labels: enhancement

#1389 Contribution Guide: Portal RI tooltip & Policies Wiki Updates
  docs/wiki/ALZ-Contribution-Guide.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  docs/wiki/media/alz-contrib-portal1.png
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-MachineLearning-PublicNetworkAccess.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-MgmtPorts-From-Internet.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-PublicEndpoint-MariaDB.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-PublicIP.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-RDP-From-Internet.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Nsg-FlowLogs-to-LA.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Nsg-FlowLogs.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Sql-Tde.json
Labels: documentation, PR: Safe to test :test_tube:

#1390 The Policy Testing Framework - DENY
  .github/workflows/alz-policy-tests.yml
  .github/workflows/test-portal.yml
  .github/workflows/unit-test-policies.yml
  docs/wiki/ALZ-Contribution-Guide.md
  docs/wiki/Whats-new.md
  docs/wiki/media/ALZ Policy Assignments v2.xlsx
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-PostgreSql-http.json
  tests/policy/Deny-AA-child-resources.Tests.ps1.TODO
  tests/policy/Deny-AppGW-Without-WAF.Tests.ps1
  tests/policy/Deny-AppServiceApiApp-http.Tests.ps1
  tests/policy/Deny-AppServiceFunctionApp-http.Tests.ps1
  tests/policy/Deny-AppServiceWebApp-http.Tests.ps1
  tests/policy/Deny-FileServices-InsecureAuth.Tests.ps1
  tests/policy/Deny-FileServices-InsecureKerberos.Tests.ps1
  tests/policy/Deny-FileServices-InsecureSmbChannel.Tests.ps1
  tests/policy/Deny-FileServices-InsecureSmbVersions.Tests.ps1
  tests/policy/Deny-MgmtPorts-From-Internet.Tests.ps1
  tests/policy/Deny-MySql-http.Tests.ps1
  tests/policy/Deny-PostgreSql-http.Tests.ps1
  tests/policy/Deny-Private-DNS-Zones.Tests.ps1
  tests/policy/Deny-Redis-http.Tests.ps1.TODO
  tests/policy/Deny-Storage-SFTP.Tests.ps1
  tests/policy/Deny-Storage-minTLS.Tests.ps1
  tests/policy/Deny-StorageAccount-CustomDomain.Tests.ps1
  tests/policy/Deny-Subnet-Without-Nsg.Tests.ps1
  tests/policy/Deny-Subnet-Without-Penp.Tests.ps1
  tests/policy/Deny-Subnet-Without-Udr.Tests.ps1
  tests/policy/Deny-UDR-With-Specific-NextHop.Tests.ps1
  tests/policy/Deny-VNET-Peer-Cross-Sub.Tests.ps1
  tests/policy/Deny-VNET-Peering-To-Non-Approved-VNETs.Tests.ps1
  tests/policy/Deny-VNet-Peering.Tests.ps1
  tests/utils/Generic.Utils.psm1
  tests/utils/Policy.Utils.psm1
  tests/utils/Rest.Utils.psm1
  tests/utils/Test.Utils.psm1
Labels: enhancement, policy, engineering, PR: Safe to test :test_tube:

#1394 Update workflow to 10.1
  .github/workflows/test-portal.yml
Labels: PR: Safe to test :test_tube:
