Repository Azure/Enterprise-Scale, pull requests merged in 2023-02, with the labels that each got.

#1195 Add January External Community Call Media
  docs/wiki/Community-Calls.md
  docs/wiki/Whats-new.md
  docs/wiki/media/community-calls/jan-2023/ALZ-Community-Call-31012023.pdf
  docs/wiki/media/community-calls/jan-2023/alz-jan-2023-youtube-screenshot.png
Labels: documentation

#1198 updating docs
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/Whats-new.md
Labels: bug, documentation

#1205 Fix #1204 Image Link Broken
  docs/reference/adventureworks/README.md
Labels: documentation

#1206 Add rule to ask Jeff to review if portal change on main
  .github/fabricbot.json
Labels: enhancement, engineering

#1201 Add deny create classic resources policy
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/fairfaxeslz-portal.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-ClassicResourceTypesPolicyAssignment.json
Labels: policy

#1211 Updated references from docs.microsoft.com - to learn
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  SECURITY.md
  SUPPORT.md
  docs/Deploy/deploy-lz-vnet.md
  docs/Deploy/deploy-policy-driven-routing.md
  docs/Deploy/es-schema.md
  docs/reference/Readme.md
  docs/reference/adventureworks/README.md
  docs/reference/contoso/Readme.md
  docs/reference/treyresearch/README.md
  docs/reference/wingtip/README.md
  docs/wiki/ALZ-Architecture.md
  docs/wiki/ALZ-Contribution-Guide.md
  docs/wiki/ALZ-Deploy-landing-zones.md
  docs/wiki/ALZ-Deploy-reference-implementations.md
  docs/wiki/ALZ-Deploy-workloads.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/ALZ-Setup-aad-permissions.md
  docs/wiki/ALZ-Setup-azure.md
  docs/wiki/Create-Landingzones.md
  docs/wiki/Deploying-ALZ-BasicSetup.md
  docs/wiki/Deploying-ALZ-VWAN.md
  docs/wiki/FAQ.md
  docs/wiki/What-is-Enterprise-Scale.md
  docs/wiki/Whats-new.md
  eslzArm/README.md
  examples/landing-zones/subscription-with-rbac/README.md
  workloads/AKS/README.md
  workloads/ARO/README.md
  workloads/keyvault/README.md
Labels: Needs: Triage :mag:

#1189 Initiative implementation for Decommissioned/Sandbox LZ
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-ALZ-DecommissionedPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyAssignments/ENFORCE-ALZ-SandboxPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Vm-autoShutdown.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-ALZ-Decomm.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-ALZ-Sandbox.json
  src/templates/policies.bicep
Labels: enhancement, policy, engineering

#1216 AppService Diagnostics Settings depend on the Tier
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Website.json
Labels: bug, enhancement, policy

#1219 Updated policy for VPN gateway diagnostic settings
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-VNetGW.json
Labels: bug, policy

#1223 [Wiki] Smaller fixes / suggestions
  docs/wiki/ALZ-Architecture.md
  docs/wiki/What-is-Enterprise-Scale.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
Labels: documentation

#1224 [Wiki] Several 'How-Enterprise-Scale-Works' & 'ALZ-Setup-aad-permissions' documentation-specific suggestions
  docs/wiki/ALZ-Deploy-reference-implementations.md
  docs/wiki/ALZ-Setup-aad-permissions.md
  docs/wiki/How-Enterprise-Scale-Works.md
Labels: documentation

#1220 Policy: Deny VM Unmanaged Disks
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
  eslzArm/eslzArm.test.param.json
  eslzArm/managementGroupTemplates/policyAssignments/DENY-VMUnmanagedDiskPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  eslzArm/managementGroupTemplates/roleDefinitions/customRoleDefinitions.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deny-VMUnmanagedDisk.json
  src/templates/policies.bicep
Labels: enhancement, policy

#1193 Replace "Auditing on SQL server should be enabled" with "Configure SQL servers to have auditing enabled to Log Analytics workspace" - AINE to DINE - for ADO 26000
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/DINE-SQLAuditingPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
Labels: enhancement, do not merge, policy, engineering

#1222 Update diagnostics policies
  docs/wiki/Whats-new.md
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Databricks.json
  src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-PostgreSQL.json
Labels: enhancement, policy, external community contribution

#1227 Pin to Az PowerShell Module Version 9.4.0 for #1199
  .github/workflows/test-portal.yml
Labels: bug, engineering

#1210 unused resources cost optimization policy and set
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
  eslzArm/eslzArm.json
  eslzArm/managementGroupTemplates/policyAssignments/AUDIT-UnusedResourcesPolicyAssignment.json
  eslzArm/managementGroupTemplates/policyDefinitions/policies.json
  src/resources/Microsoft.Authorization/policyDefinitions/Audit-Disks-UnusedResourcesCostOptimization.json
  src/resources/Microsoft.Authorization/policyDefinitions/Audit-PublicIpAddresses-UnusedResourcesCostOptimization.json
  src/resources/Microsoft.Authorization/policyDefinitions/Audit-ServerFarms-UnusedResourcesCostOptimization.json
  src/resources/Microsoft.Authorization/policySetDefinitions/Audit-UnusedResourcesCostOptimization.json
  src/templates/policies.bicep
Labels: enhancement, policy

#1228 fix: Update MG location parameter name
  docs/wiki/Update-ALZ-Custom-Policies-to-Latest.md
Labels: Needs: Triage :mag:

#1231 Update Invoke-AlzCustomPolicyCheckAgainstBuiltIn.ps1
  src/scripts/Invoke-AlzCustomPolicyCheckAgainstBuiltIn.ps1
Labels: enhancement, engineering
