Repository Azure/Enterprise-Scale, pull requests merged in 2024-09, with the labels that each got.

#1751 AMBA Enhanced Feature Portal Update
  docs/wiki/Whats-new.md
  eslzArm/eslz-portal.json
  eslzArm/eslzArm.json
Labels: PR: Safe to test :test_tube:

#1756 Updated documentation for Azure Monitor Baseline Alerts Initiatives
  docs/wiki/ALZ-Deprecated-Services.md
  docs/wiki/ALZ-Policies.md
  docs/wiki/Whats-new.md
Labels: documentation

#1755 Portal test update
  .github/workflows/test-portal.yml
  eslzArm/eslzArm.test.param.hns.json
  eslzArm/eslzArm.test.param.std.json
  eslzArm/eslzArm.test.param.vwan.json
  utils/github/alz-repo-standard-labels.csv
Labels: Needs: Author Feedback
